name: Publish Package

on:
  release:
    types: [published]

permissions:
  contents: read


jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://pypi.org/p/hyperiax
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Build package
      run: python setup.py sdist
     # working-directory: ./app


    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}